// default package
// Generated Sep 20, 2015 6:10:57 PM by Hibernate Tools 4.3.1
package com.hibernate.project;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Customer generated by hbm2java
 */
@Entity
@Table(name = "customer", catalog = "projectwebservices")
public class Customer implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer customerId;
	private String customerName;
	private String customerAddress;
	private int customerZipcode;
	private String customerCity;
	private String customerCountry;
	private int customerCellphone;
	private Integer customerCredentials;
	private Set<Order> orders = new HashSet<Order>(0);
	private Set<PartnerComments> partnerCommentses = new HashSet<PartnerComments>(0);
	private Set<CustomerPayment> customerPayments = new HashSet<CustomerPayment>(0);
	private Set<ProductComments> productCommentses = new HashSet<ProductComments>(0);

	public Customer() {
	}

	public Customer(String customerName, String customerAddress, int customerZipcode, String customerCity,
			String customerCountry, int customerCellphone) {
		this.customerName = customerName;
		this.customerAddress = customerAddress;
		this.customerZipcode = customerZipcode;
		this.customerCity = customerCity;
		this.customerCountry = customerCountry;
		this.customerCellphone = customerCellphone;
	}

	public Customer(String customerName, String customerAddress, int customerZipcode, String customerCity,
			String customerCountry, int customerCellphone, Integer customerCredentials, Set<Order> orders,
			Set<PartnerComments> partnerCommentses, Set<CustomerPayment> customerPayments,
			Set<ProductComments> productCommentses) {
		this.customerName = customerName;
		this.customerAddress = customerAddress;
		this.customerZipcode = customerZipcode;
		this.customerCity = customerCity;
		this.customerCountry = customerCountry;
		this.customerCellphone = customerCellphone;
		this.customerCredentials = customerCredentials;
		this.orders = orders;
		this.partnerCommentses = partnerCommentses;
		this.customerPayments = customerPayments;
		this.productCommentses = productCommentses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Customer_ID", unique = true, nullable = false)
	public Integer getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(Integer customerId) {
		this.customerId = customerId;
	}

	@Column(name = "Customer_Name", nullable = false, length = 45)
	public String getCustomerName() {
		return this.customerName;
	}

	public void setCustomerName(String customerName) {
		this.customerName = customerName;
	}

	@Column(name = "Customer_Address", nullable = false, length = 45)
	public String getCustomerAddress() {
		return this.customerAddress;
	}

	public void setCustomerAddress(String customerAddress) {
		this.customerAddress = customerAddress;
	}

	@Column(name = "Customer_Zipcode", nullable = false)
	public int getCustomerZipcode() {
		return this.customerZipcode;
	}

	public void setCustomerZipcode(int customerZipcode) {
		this.customerZipcode = customerZipcode;
	}

	@Column(name = "Customer_City", nullable = false, length = 45)
	public String getCustomerCity() {
		return this.customerCity;
	}

	public void setCustomerCity(String customerCity) {
		this.customerCity = customerCity;
	}

	@Column(name = "Customer_Country", nullable = false, length = 45)
	public String getCustomerCountry() {
		return this.customerCountry;
	}

	public void setCustomerCountry(String customerCountry) {
		this.customerCountry = customerCountry;
	}

	@Column(name = "Customer_Cellphone", nullable = false)
	public int getCustomerCellphone() {
		return this.customerCellphone;
	}

	public void setCustomerCellphone(int customerCellphone) {
		this.customerCellphone = customerCellphone;
	}

	@Column(name = "Customer_Credentials")
	public Integer getCustomerCredentials() {
		return this.customerCredentials;
	}

	public void setCustomerCredentials(Integer customerCredentials) {
		this.customerCredentials = customerCredentials;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customer")
	public Set<Order> getOrders() {
		return this.orders;
	}

	public void setOrders(Set<Order> orders) {
		this.orders = orders;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customer")
	public Set<PartnerComments> getPartnerCommentses() {
		return this.partnerCommentses;
	}

	public void setPartnerCommentses(Set<PartnerComments> partnerCommentses) {
		this.partnerCommentses = partnerCommentses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customer")
	public Set<CustomerPayment> getCustomerPayments() {
		return this.customerPayments;
	}

	public void setCustomerPayments(Set<CustomerPayment> customerPayments) {
		this.customerPayments = customerPayments;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customer")
	public Set<ProductComments> getProductCommentses() {
		return this.productCommentses;
	}

	public void setProductCommentses(Set<ProductComments> productCommentses) {
		this.productCommentses = productCommentses;
	}

}
