// default package
// Generated Sep 20, 2015 6:10:57 PM by Hibernate Tools 4.3.1
package com.hibernate.project;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CustomerPayment generated by hbm2java
 */
@Entity
@Table(name = "customer_payment", catalog = "projectwebservices")
public class CustomerPayment implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer customerPaymentId;
	private Customer customer;
	private String customerPaymentDescription;
	private String customerPaymentBilling;
	private Set<Order> orders = new HashSet<Order>(0);

	public CustomerPayment() {
	}

	public CustomerPayment(Customer customer, String customerPaymentDescription, String customerPaymentBilling) {
		this.customer = customer;
		this.customerPaymentDescription = customerPaymentDescription;
		this.customerPaymentBilling = customerPaymentBilling;
	}

	public CustomerPayment(Customer customer, String customerPaymentDescription, Set<Order> orders) {
		this.customer = customer;
		this.customerPaymentDescription = customerPaymentDescription;
		this.orders = orders;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Customer_Payment_ID", unique = true, nullable = false)
	public Integer getCustomerPaymentId() {
		return this.customerPaymentId;
	}

	public void setCustomerPaymentId(Integer customerPaymentId) {
		this.customerPaymentId = customerPaymentId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Customer_FK", nullable = false)
	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	@Column(name = "Customer_Payment_Description", nullable = false, length = 45)
	public String getCustomerPaymentDescription() {
		return this.customerPaymentDescription;
	}

	public void setCustomerPaymentDescription(String customerPaymentDescription) {
		this.customerPaymentDescription = customerPaymentDescription;
	}

	@Column(name = "Customer_Payment_Billing", length = 45)
	public String getCustomerPaymentBilling() {
		return this.customerPaymentBilling;
	}

	public void setCustomerPaymentBilling(String customerPaymentBilling) {
		this.customerPaymentBilling = customerPaymentBilling;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customerPayment")
	public Set<Order> getOrders() {
		return this.orders;
	}

	public void setOrders(Set<Order> orders) {
		this.orders = orders;
	}

}
