// default package
// Generated Sep 20, 2015 6:10:57 PM by Hibernate Tools 4.3.1
package com.hibernate.project;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Partner generated by hbm2java
 */
@Entity
@Table(name = "partner", catalog = "projectwebservices")
public class Partner implements java.io.Serializable {

	private Integer partnerId;
	private String partnerName;
	private String partnerAddress;
	private String partnerZipcode;
	private String partnerCity;
	private String partnerCountry;
	private String partnerCellphone;
	private Integer partnerCredentials;
	private Set<Product> products = new HashSet<Product>(0);
	private Set<PartnerComments> partnerCommentses = new HashSet<PartnerComments>(0);

	public Partner() {
	}

	public Partner(String partnerName, String partnerAddress, String partnerZipcode, String partnerCity,
			String partnerCountry, String partnerCellphone) {
		this.partnerName = partnerName;
		this.partnerAddress = partnerAddress;
		this.partnerZipcode = partnerZipcode;
		this.partnerCity = partnerCity;
		this.partnerCountry = partnerCountry;
		this.partnerCellphone = partnerCellphone;
	}

	public Partner(String partnerName, String partnerAddress, String partnerZipcode, String partnerCity,
			String partnerCountry, String partnerCellphone, Integer partnerCredentials, Set<Product> products,
			Set<PartnerComments> partnerCommentses) {
		this.partnerName = partnerName;
		this.partnerAddress = partnerAddress;
		this.partnerZipcode = partnerZipcode;
		this.partnerCity = partnerCity;
		this.partnerCountry = partnerCountry;
		this.partnerCellphone = partnerCellphone;
		this.partnerCredentials = partnerCredentials;
		this.products = products;
		this.partnerCommentses = partnerCommentses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Partner_ID", unique = true, nullable = false)
	public Integer getPartnerId() {
		return this.partnerId;
	}

	public void setPartnerId(Integer partnerId) {
		this.partnerId = partnerId;
	}

	@Column(name = "Partner_Name", nullable = false, length = 45)
	public String getPartnerName() {
		return this.partnerName;
	}

	public void setPartnerName(String partnerName) {
		this.partnerName = partnerName;
	}

	@Column(name = "Partner_Address", nullable = false, length = 45)
	public String getPartnerAddress() {
		return this.partnerAddress;
	}

	public void setPartnerAddress(String partnerAddress) {
		this.partnerAddress = partnerAddress;
	}

	@Column(name = "Partner_Zipcode", nullable = false, length = 45)
	public String getPartnerZipcode() {
		return this.partnerZipcode;
	}

	public void setPartnerZipcode(String partnerZipcode) {
		this.partnerZipcode = partnerZipcode;
	}

	@Column(name = "Partner_City", nullable = false, length = 45)
	public String getPartnerCity() {
		return this.partnerCity;
	}

	public void setPartnerCity(String partnerCity) {
		this.partnerCity = partnerCity;
	}

	@Column(name = "Partner_Country", nullable = false, length = 45)
	public String getPartnerCountry() {
		return this.partnerCountry;
	}

	public void setPartnerCountry(String partnerCountry) {
		this.partnerCountry = partnerCountry;
	}

	@Column(name = "Partner_Cellphone", nullable = false, length = 45)
	public String getPartnerCellphone() {
		return this.partnerCellphone;
	}

	public void setPartnerCellphone(String partnerCellphone) {
		this.partnerCellphone = partnerCellphone;
	}

	@Column(name = "Partner_Credentials")
	public Integer getPartnerCredentials() {
		return this.partnerCredentials;
	}

	public void setPartnerCredentials(Integer partnerCredentials) {
		this.partnerCredentials = partnerCredentials;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "partner")
	public Set<Product> getProducts() {
		return this.products;
	}

	public void setProducts(Set<Product> products) {
		this.products = products;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "partner")
	public Set<PartnerComments> getPartnerCommentses() {
		return this.partnerCommentses;
	}

	public void setPartnerCommentses(Set<PartnerComments> partnerCommentses) {
		this.partnerCommentses = partnerCommentses;
	}

}
