// default package
// Generated Sep 20, 2015 6:10:57 PM by Hibernate Tools 4.3.1
package com.hibernate.project;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PartnerComments generated by hbm2java
 */
@Entity
@Table(name = "partner_comments", catalog = "projectwebservices")
public class PartnerComments implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer partnerCommentsId;
	private Customer customer;
	private Partner partner;
	private String partnerComments;

	public PartnerComments() {
	}

	public PartnerComments(Customer customer, Partner partner, String partnerComments) {
		this.customer = customer;
		this.partner = partner;
		this.partnerComments = partnerComments;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Partner_Comments_ID", unique = true, nullable = false)
	public Integer getPartnerCommentsId() {
		return this.partnerCommentsId;
	}

	public void setPartnerCommentsId(Integer partnerCommentsId) {
		this.partnerCommentsId = partnerCommentsId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Customer_FK", nullable = false)
	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Partner_FK", nullable = false)
	public Partner getPartner() {
		return this.partner;
	}

	public void setPartner(Partner partner) {
		this.partner = partner;
	}

	@Column(name = "Partner_Comments", nullable = false, length = 200)
	public String getPartnerComments() {
		return this.partnerComments;
	}

	public void setPartnerComments(String partnerComments) {
		this.partnerComments = partnerComments;
	}

}
