// default package
// Generated Sep 20, 2015 6:10:57 PM by Hibernate Tools 4.3.1
package com.hibernate.project;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ProductComments generated by hbm2java
 */
@Entity
@Table(name = "product_comments", catalog = "projectwebservices")
public class ProductComments implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer productCommentsId;
	private Customer customer;
	private Product product;
	private String productComments;

	public ProductComments() {
	}

	public ProductComments(Customer customer, Product product, String productComments) {
		this.customer = customer;
		this.product = product;
		this.productComments = productComments;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Product_Comments_ID", unique = true, nullable = false)
	public Integer getProductCommentsId() {
		return this.productCommentsId;
	}

	public void setProductCommentsId(Integer productCommentsId) {
		this.productCommentsId = productCommentsId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Customer_FK", nullable = false)
	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Product_FK", nullable = false)
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@Column(name = "Product_Comments", nullable = false, length = 200)
	public String getProductComments() {
		return this.productComments;
	}

	public void setProductComments(String productComments) {
		this.productComments = productComments;
	}

}
